name: CI

on:
  - push

jobs:
  build:
    name: Linux-${{ matrix.arch }}
    runs-on: ${{ matrix.runs-on }}
    permissions:
      security-events: write
      contents: read
    strategy:
      matrix:
        include:
          - arch: amd64
            runs-on: ubuntu-22.04
          - arch: aarch64
            runs-on: ubuntu-22.04-arm
    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - name: uname -a
        run: uname -a

      - name: cat /etc/os-release
        run: cat /etc/os-release

      - name: install required packages
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - name: build project
        run: ninja

      - name: test binary
        run: ./polyfill-glibc polyfill-glibc --print-imports

      - name: rename binary
        run: mv polyfill-glibc polyfill-glibc-${{ matrix.arch }}

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: polyfill-glibc-${{ matrix.arch }}
          path: ./polyfill-glibc-${{ matrix.arch }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      packages: write
      security-events: write
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v5

      - name: create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          commit: ${{ github.sha }}
          artifactErrorsFailBuild: true
          artifacts: polyfill-glibc-*/polyfill-glibc-*
          body: "Generated from commit ${{ github.sha }} on branch ${{ github.ref_name }}"
